### ISSUE TITLE
Issue with ImageNet Example

### ISSUE THREAD

**Issue by rahulbhalerao001** [amplab/SparkNet#63] opened 2016-02-13 10:22 UTC
Hello,

I followed all the steps of the example including those in the issue, but my execution is getting stuck at a point. It is able to preprocess the training data but gets stuck in preprocessing the validation data. For the validation data, I downloaded the tar, untarred it, and repacked them into tars of around 250MB each, and then uploaded to S3. However, I am afraid I may have shuffled the order of images in this process.

Due to this or some other reason, the preprocessing step for validation data remains stuck indefinitely, however preprocessing of all the train data gets completed in 20 min. I am using 2 g2.8xlarge machines as slaves, which remain at high usage during the time the execution is stuck. Any tips on debugging or resolving this issue will be greatly appreciated. I have tried with both persist() and persist(StorageLevel.MEMORY_AND_DISK).

As shown below, it gets stuck after launching 26 tasks for the 25 tars of val data.

```
16/02/13 09:48:27 INFO scheduler.DAGScheduler: Submitting 26 missing tasks from ResultStage 0 (MapPartitionsRDD[4] at mapPartitions at ScaleAndConvert.scala:31)
16/02/13 09:48:27 INFO scheduler.TaskSchedulerImpl: Adding task set 0.0 with 26 tasks
16/02/13 09:48:27 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, 172.31.16.22, PROCESS_LOCAL, 2221 bytes)
16/02/13 09:48:27 INFO scheduler.TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, 172.31.25.24, PROCESS_LOCAL, 2228 bytes)
..
..
16/02/13 09:48:27 INFO scheduler.TaskSetManager: Starting task 25.0 in stage 0.0 (TID 25, 172.31.25.24, PROCESS_LOCAL, 2228 bytes)
16/02/13 09:48:27 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 172.31.16.22:43854 (size: 1742.0 B, free: 27.4 GB)
16/02/13 09:48:27 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 172.31.25.24:38520 (size: 1742.0 B, free: 27.4 GB)
16/02/13 09:48:28 INFO storage.BlockManagerInfo: Added rdd_4_0 in memory on 172.31.16.22:43854 (size: 24.0 B, free: 27.4 GB)
16/02/13 09:48:28 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1503 ms on 172.31.16.22 (1/26)

```

Also, on a related note I will like to point out 2-3 points that were not present in the Readme and which lead to errors on running the example.
1. Creation of a /tmp/spark-events/ directory is required else it leads to an error.
2. The readme states that the ~/.aws/credentials is required only on the master but not on the slaves. However, while running the example it is required on all the machines.
3. After changing the S3 bucket name, the Sparknet project needs to be rebuilt using 'sbt assembly'. This was not specified in the Readme. Further, the issue states that name of the validation folders is actually test, but in the version of the project present in the AMI, the names are actually val.txt and IL..._va

**Comment by robertnishihara** [comment] 2016-02-13 19:40
Hi Rahul, thanks for being so thorough! You're right about the omissions from the README. I'll add those and create an updated AMI.

Also, you're right that untarring and then retarring the validation files is a bit of a mess. I think we'll rewrite stuff to allow people to put `ILSVRC2012_img_var.tar` on S3 directly.

It's possible that the problem you're seeing is due to the way the validation files are tarred, but it's also possible that it's slow because of the size of the data. One way to check this is to replace the lines
```scala
var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/", "train.txt")
val testRDD = loader.apply(sc, "ILSVRC2012_img_val/", "val.txt")
```
with
```scala
var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/n01", "train.txt")
val testRDD = loader.apply(sc, "ILSVRC2012_img_val/validation.0", "val.txt")
```
or with
```scala
var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/n015", "train.txt")
val testRDD = loader.apply(sc, "ILSVRC2012_img_val/validation.00", "val.txt")
```
When you use `"ILSVRC2012_img_train/n01"`, that selects the training tar files whose filenames begin with `n01` (I believe 127 out of 1000 tar files). If you use `"ILSVRC2012_img_train/n015"`, it selects the training tar files whose filenames begin with `n015`, (13 out of 1000 tar files).

Similarly, `"ILSVRC2012_img_val/validation.0"` should select the validation tar files whose filenames begin with `validation.0` (10 of them). And `"ILSVRC2012_img_val/validation.00"` should select the validation tar files whose filenames begin with `validation.00` (only 1 of them).

This allows you to see if things work with much less data. If that works, then the problem has to do with the size of the data (and maybe using more nodes would help). If it fails, then the problem is somewhere else (possibly with the way the validation files are tarred).

Let me know how that goes!

**Comment by rahulbhalerao001** [comment] 2016-02-15 20:50
Hello Robert,

Thank you for making the instructions easier. 
About the problem I had initially put up, it was because I had created a tar of a directory. So in the ImageNetLoader code, if it is directory, it continues in a busy loop, this explains the high CPU usage on the nodes when the execution was stuck.
`        while (entry != null) {
          if (!entry.isDirectory) {
            var offset = 0
            var ret = 0
            val content = new Array[Byte](entry.getSize().toInt)
            while (ret >= 0 && offset != entry.getSize()) {
              ret = tarStream.read(content, offset, content.length - offset)
              if (ret >= 0) {
                offset += ret
              }
            }
            // load the image data
            val filename = Paths.get(entry.getName()).getFileName().toString
            images += ((content, broadcastMap.value(filename)))
            entry = tarStream.getNextTarEntry()
          }
        }`

Thanks,
Rahul

**Comment by rahulbhalerao001** [comment] 2016-02-15 21:02
However, after resolving that issue, I ran into multiple other issues. The initial AMI had the code at https://github.com/amplab/SparkNet/commit/0a6aaaa280b0d9f9118e15bebffe149b0dccb07f state and I also tried updating to this state https://github.com/amplab/SparkNet/commit/e5ee2c3caaa203ed614557ff5100f9d0fa5020ec  (which was latest till yesterday).

The train and val data pre processing steps went fine, the training also started but the reduce for testing got stuck. This happened multiple times, so I tried with both versions of the code. As you had suggested I limited train data to only those with prefix n01 (n015 prefix gives an error that n must be positive) and increased the number of g2.8xlarge slaves from2 to 5. Further I tried with java heap memory of 8GB and 32 GB. But in all these combinations, I was never able to complete the execution. Sometimes there were intermittent errors that data not serializable. 
But the pertinent error was getting stuck in the reduce state of testing, and then one of the executors used to get lost even if the EC2 instance was in running state.

I am benchmarking the application to study its network properties, but unfortunately on multiple attempts, I was not able to pass beyond the first iteration of train, update and test.

I wanted to know whether I can use my already uploaded data to S3 using the new AMI and code or will it be better to reupload as per the new instruction steps.

**Comment by robertnishihara** [comment] 2016-02-15 22:58
Hi Rahul,

A couple questions/comments:

1. Have you tried the CifarApp? And if so, did that work? That one should be much easier to get running because you don't have to deal with S3. And if that doesn't work, it will be easier for us to track down the problem.
2. I'd suggest deleting all of the ImageNet data from S3 and uploading it again with the script `SparkNet/scripts/put_imagenet_on_s3.py` (this will take several hours, but at least it will ensure that we are dealing with the same directory structure and file names).
3. I'm not sure about the serialization error at the moment, but let me give it some thought.

**Comment by rahulbhalerao001** [comment] 2016-02-15 23:01
Hello Robert,

Thank you for responding.
Thank you for your prompt response and patience.
1. Yes, CifarApp runs perfectly for me.
2. I will delete all the ImageNet data and start from scratch with new data and new AMI.
3. I am sorry I am giving  only vague details about the bug, but unfortunately, I lost my logs due to termination of the instances. So please ignore it for now, I will try as per Step 2, and report the status.
Thanks,
Rahul

**Comment by rahulbhalerao001** [comment] 2016-02-15 23:48
OK, a small question - If we directly use the AMI do we still need to follow the steps in SETUP? I think I might have missed creating and attaching the instance volume to the slaves and so the nodes might be getting stuck when their memory gets full. 
I was under the impression that those steps are not required, my bad. Do we also need to build caffe as per step 3?

**Comment by robertnishihara** [comment] 2016-02-16 04:29
Good point, we need to clarify this. If you're using the AMI, then you should only need to follow the instructions under "ImageNet" in the README. For now, I'd suggest using a fraction of the ImageNet dataset (e.g., 1% or 10%) so that you can ignore the part about mounting extra volumes. Once that's working, then we can use the full dataset (and that will probably require extra volumes or more memory).

You will probably also need to update the SparkNet repository on the AMI to the current master, and run "sbt assembly" again to recompile.

If you come across any error messages, please post them here!

We are working on simplifying the setup process, so hopefully that will be done soon and everything will get a lot easier.

**Comment by rahulbhalerao001** [comment] 2016-02-16 04:44
Hello Robert,

I am using the new AMI now - ami-c0dd7db3.
After manually installing boto3 and pillow, I am trying to run the python script for uploading data but I am running into the following error. I tried when both the bucket was manually created and when it was not.

Command

`python $SPARKNET_HOME/scripts/put_imagenet_on_s3.py sparknetdivideo \
    --train_tar_file=~/data/ILSVRC2012_img_train.tar \
    --val_tar_file=~/data/ILSVRC2012_img_val.tar \
    --new_width=256 \
    --new_height=256`
`

Error 
`
Traceback (most recent call last):
  File "/root/SparkNet//scripts/put_imagenet_on_s3.py", line 108, in <module>
    upload_file("train.txt", train_label_file.read())
  File "/root/SparkNet//scripts/put_imagenet_on_s3.py", line 39, in upload_file
    s3.put_object(Bucket=args.s3_bucket, Key=targetname, Body=stream)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 396, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 213, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))`

**Comment by robertnishihara** [comment] 2016-02-16 04:47
I've seen this error. I think it may have gone away after I did `pip install aws --upgrade`. Can you try that? Also perhaps try `pip install boto3 --upgrade`.

**Comment by rahulbhalerao001** [comment] 2016-02-16 04:48
Ok, I will try that. But from the same machine,
`aws s3 cp test s3://sparknetdivideo`
is successful.

**Comment by rahulbhalerao001** [comment] 2016-02-16 04:52
No help, same status.

`root@ip-172-31-25-218:~/SparkNet# pip install boto3 --upgrade
Requirement already up-to-date: boto3 in /usr/local/lib/python2.7/dist-packages
Cleaning up...`

`root@ip-172-31-25-218:~/SparkNet# pip install aws --upgrade
Requirement already up-to-date: aws in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: boto in /usr/local/lib/python2.7/dist-packages (from aws)
Requirement already up-to-date: fabric>=1.6 in /usr/local/lib/python2.7/dist-packages (from aws)
Requirement already up-to-date: prettytable>=0.7 in /usr/lib/python2.7/dist-packages (from aws)
Cleaning up...`

`root@ip-172-31-25-218:~/SparkNet# python $SPARKNET_HOME/scripts/put_imagenet_on_s3.py sparknetdivideo1     --train_tar_file=~/data/ILSVRC2012_img_train.tar     --val_tar_file=~/data/ILSVRC2012_img_val.tar     --new_width=256     --new_height=256
starting to upload train.txt to bucket sparknetdivideo1
Traceback (most recent call last):
  File "/root/SparkNet//scripts/put_imagenet_on_s3.py", line 108, in <module>
    upload_file("train.txt", train_label_file.read())
  File "/root/SparkNet//scripts/put_imagenet_on_s3.py", line 39, in upload_file
    s3.put_object(Bucket=args.s3_bucket, Key=targetname, Body=stream)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 396, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 213, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))`

**Comment by rahulbhalerao001** [comment] 2016-02-16 04:54
If you feel this is my instance specific issue, please ignore it for now. I will try out a few things on my end.

**Comment by robertnishihara** [comment] 2016-02-16 05:28
Hmm.. I'll let you know if I think of something. I just experienced that problem yesterday and eventually got it to go away (but now I can't recreate it).

I thought it might be a problem with Anaconda, but it works for me with both Anaconda and the system's python.

Running `pip show aws` prints
```
Metadata-Version: 2.0
Name: boto3
Version: 1.2.3
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /root/anaconda2/lib/python2.7/site-packages
Requires: jmespath, futures, botocore
```

Running `pip show boto3` prints
```
Metadata-Version: 2.0
Name: boto3
Version: 1.2.3
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /root/anaconda2/lib/python2.7/site-packages
Requires: jmespath, futures, botocore
```

**Comment by rahulbhalerao001** [comment] 2016-02-16 05:37
I seem to have a old version of aws, but when upgraded, it shows that its up to date.

`root@ip-172-31-25-218:~/SparkNet/scripts# pip show aws
---
Name: aws
Version: 0.2.5
Location: /usr/local/lib/python2.7/dist-packages
Requires: boto, fabric, prettytable
root@ip-172-31-25-218:~/SparkNet/scripts# pip show boto3
---
Name: boto3
Version: 1.2.3
Location: /usr/local/lib/python2.7/dist-packages
Requires: botocore, jmespath, futures
root@ip-172-31-25-218:~/SparkNet/scripts# `

Secondly, I tried uploading files using boto3 to S3 from python console. It was successful in doing so. I think I am very near to solving my issue. Thanks for your help.

**Comment by robertnishihara** [comment] 2016-02-16 05:41
That's good to hear, keep us posted either way!

**Comment by rahulbhalerao001** [comment] 2016-02-16 05:51
Ok, so instead of untarring the files in code, untarring it manually and passing the file handles i.e. f in 
`f = open("test.txt)`
as Stream in s3.put_object seemed to solve the issue atleast for train and test.txt. Now the script has is running, so I guess it should run to completion.

**Comment by robertnishihara** [comment] 2016-02-16 07:32
Cool. I'm interested in knowing if it runs to completion.

This'll be helpful if more people run into this error, in which case we'll need to robustify the script against this kind of thing.

**Comment by rahulbhalerao001** [comment] 2016-02-16 17:06
Ok, so I had left it running overnight. The script finished uploading the last val tar at around 3.00 AM PST. Today, I will go ahead and run the actual training program.

**Comment by robertnishihara** [comment] 2016-02-16 17:10
Awesome, let me know how that goes!

**Comment by rahulbhalerao001** [comment] 2016-02-16 20:09
Cluster creation command

`SparkNet/ec2/spark-ec2 --key-pair=newtrial --identity-file=newtrial.pem --region=eu-west-1 --zone=eu-west-1c --instance-type=g2.8xlarge --ami=ami-c0dd7db3 -s 5 --copy-aws-credentials --spark-version 1.5.0 --no-ganglia --user-data SparkNet/ec2/cloud-config.txt launch sparknet`

Job Submit Command
`/root/spark/bin/spark-submit --class apps.ImageNetApp $SPARKNET_HOME/target/scala-2.10/sparknet-assembly-0.1-SNAPSHOT.jar 5 sparknetdivideo > log.txt 2> log.txt`

Error

`16/02/16 20:05:26 WARN scheduler.TaskSetManager: Lost task 3.0 in stage 9.0 (TID 64, 172.31.23.74): java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Random.java:300)
        at scala.util.Random.nextInt(Random.scala:65)
        at libs.MinibatchSampler.<init>(MinibatchSampler.scala:18)
        at apps.ImageNetApp$$anonfun$main$3.apply(ImageNetApp.scala:181)
        at apps.ImageNetApp$$anonfun$main$3.apply(ImageNetApp.scala:157)
        at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:99)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by rahulbhalerao001** [comment] 2016-02-16 20:12
![screenshot from 2016-02-16 12 11 28](https://cloud.githubusercontent.com/assets/4405642/13089660/8a7b77ca-d4a6-11e5-83dd-a51046c38519.png)

**Comment by rahulbhalerao001** [comment] 2016-02-16 20:44
I tried adding two debug statements and divided the syncInterval by 2 before passing it to the MinibatchSampler and now getting another error.

`log("Minbatch sampler len", len)
 log("Minbatch sampler syncinterval", syncInterval)
 val minibatchSampler = new MinibatchSampler(trainMinibatchIt, len, syncInterval/2)
`

`
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2021)
        at org.apache.spark.rdd.RDD$$anonfun$zipPartitions$1.apply(RDD.scala:849)
        at org.apache.spark.rdd.RDD$$anonfun$zipPartitions$1.apply(RDD.scala:849)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.zipPartitions(RDD.scala:848)
        at org.apache.spark.rdd.RDD$$anonfun$zipPartitions$2.apply(RDD.scala:855)
        at org.apache.spark.rdd.RDD$$anonfun$zipPartitions$2.apply(RDD.scala:855)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.zipPartitions(RDD.scala:854)
        at apps.ImageNetApp$.main(ImageNetApp.scala:156)
        at apps.ImageNetApp.main(ImageNetApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.NotSerializableException: java.io.PrintWriter
Serialization stack:
        - object not serializable (class: java.io.PrintWriter, value: java.io.PrintWriter@1171b886)
        - field (class: apps.ImageNetApp$$anonfun$main$3, name: trainingLog$1, type: class java.io.PrintWriter)
        - object (class apps.ImageNetApp$$anonfun$main$3, <function2>)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
  at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:84)
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
        ... 26 more`

**Comment by robertnishihara** [comment] 2016-02-16 20:45
Ah, I believe the key is in the line
```
java.lang.IllegalArgumentException: n must be positive at java.util.Random.nextInt(Random.java:300)
```

This is happening within line 181 in `ImageNetApp.scala`, reproduced here:
```scala
val minibatchSampler = new MinibatchSampler(trainMinibatchIt, len, syncInterval)
```
We are trying to sample `syncInterval = 50` minibatches from a partition which has `len` minibatches. In this case, because you are probably using 1% of the ImageNet data, `len` is probably smaller than 50, so we end up calling `Random.nextInt` with a negative number. So this should be fixable either by making `syncInterval` smaller or by using more data. You can use more data by setting
```scala
    var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/train.000", "train.txt")
```
instead of 
```scala
    var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/train.0000", "train.txt")
```

As an aside, a bunch of this code is going to change. In particular, `MinibatchSampler` will go away.

**Comment by robertnishihara** [comment] 2016-02-16 20:49
The function `log` can't be put in a map call (it writes to a file that lives on the Spark master). You can use a regular `print` statement, and the output will appear on the worker logs at http://54.194.160.56:8080 (IP address taken from the screenshot you posted).

**Comment by rahulbhalerao001** [comment] 2016-02-16 20:51
Oh sorry for the second issue I just wanted to give as much info as possible.

About the first  issue about n, I was playing with this all day on Sunday. It was just that I did not see that the version in Git itself uses a subset of data. Since I had not made that change in my local code, I was assuming it used all the code, and so I thought the error might be elsewhere.

**Comment by robertnishihara** [comment] 2016-02-16 20:56
The place where we pull a subset of ImageNet is the line
```scala
var trainRDD = loader.apply(sc, "ILSVRC2012_img_train/train.0000", "train.txt")
```
Basically, the script `scripts/put_imagenet_on_s3.py` creates 1000 tar files on S3 named
```ILSVRC2012_img_train/train.00000``` through ```ILSVRC2012_img_train/train.00999```. The function `loader.apply(sc, "XXX", "train.txt")` pulls all of the files with the prefix `XXX`. This makes it easy to use 1% or 10% of the data.

**Comment by rahulbhalerao001** [comment] 2016-02-16 21:00
Yes yes,  I was aware of that. I missed looking at it when I got the error that n must be positive.

Ok for now the training is working successfully.  For training with the entire data set, do you feel that adding a volume to the slaves is necessary? If yes, does it have to be converted into ext4 before mounting as per the instructions on Amazon's documentation.

For reference 
`0.002: loading train data
6.823: loading test data
7.456: processing train data
22.104: numTrainMinibatches = 500
22.104: processing test data
27.208: numTestMinibatches = 200
27.208: computing mean image
29.202: coalescing
29.321: trainPartitionSizes = Array(100, 100, 100, 100, 100)
29.362: testPartitionSizes = Array(40, 40, 40, 40, 40)
57.879, i = 0: broadcasting weights
58.576, i = 0: setting weights on workers
62.156, i = 0: testing
70.286, i = 0: 0.08% accuracy
70.286, i = 0: training
176.556, i = 0: collecting weights
192.708, i = 1: broadcasting weights
193.422, i = 1: setting weights on workers
196.24, i = 1: training
303.133, i = 1: collecting weights
318.766, i = 2: broadcasting weights
319.4, i = 2: setting weights on workers
322.408, i = 2: training
429.262, i = 2: collecting weights
445.211, i = 3: broadcasting weights
445.834, i = 3: setting weights on workers
448.604, i = 3: training
`

**Comment by robertnishihara** [comment] 2016-02-16 21:10
I'd try it with 10% of the data and make sure that works fine.

I wouldn't bother adding volumes because Spark can be extremely slow when reading RDDs from disk. The best solution in that case might be to leave the JPEGs in the RDD (that is, don't decompress them), and then decompress them as needed for training. That might enable everything to fit in memory.

**Comment by rahulbhalerao001** [comment] 2016-02-16 21:22
Hello Robert,
Yes I tried to do with the whole data after increasing the allocated memory to 50G.
`
val conf = new SparkConf()                                        
       .setAppName("ImageNet")                                   
      .set("spark.driver.maxResultSize", "30G")                 
      .set("spark.driver.maxResultSize", "50G")                 
      .set("spark.task.maxFailures", "1")                             
     val sc = new SparkContext(conf)  
`
But it has got stuck in this phase 
![stuck](https://cloud.githubusercontent.com/assets/4405642/13091445/2462916c-d4b0-11e5-8cdf-f0a61f9dc2a1.png)

I will try out your suggested option of keeping the JPEGs in compressed format, and let you know what happens.

Thank you for your patience and support. I apologize if I have asked too many silly questions.

**Comment by rahulbhalerao001** [comment] 2016-02-16 21:32
Ok so finally it has crashed. So leaving in the compressed format is the way to go I guess.

`16/02/16 21:26:48 ERROR client.TransportResponseHandler: Still have 1 requests outstanding when connection from /172.31.23.72:47135 is closed
16/02/16 21:26:48 ERROR shuffle.RetryingBlockFetcher: Failed to fetch block taskresult_2066, and will not retry (3 retries)
java.io.IOException: Connection from /172.31.23.72:47135 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelUnregistered(TransportResponseHandler.java:104)
        at org.apache.spark.network.server.TransportChannelHandler.channelUnregistered(TransportChannelHandler.java:91)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:739)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:659)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
16/02/16 21:26:48 ERROR scheduler.TaskResultGetter: Exception while getting task result
java.io.IOException: Connection from /172.31.23.72:47135 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelUnregistered(TransportResponseHandler.java:104)
        at org.apache.spark.network.server.TransportChannelHandler.channelUnregistered(TransportChannelHandler.java:91)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
`

**Comment by robertnishihara** [comment] 2016-02-17 08:22
Hi Rahul, we just made a bunch of new changes to the code base, hopefully simplifying a number of things (see #72). There are a couple of consequences for ImageNetApp in the meantime.

- The code is simpler, and most of the clunky classes are gone (e.g., MiniBatchSampler).
- Training will be slow (we had to disable GPUs due to a bug in javacpp javacpp-presets/issues#147), but we plan on fixing this soon. This will make it difficult to train ImageNet to high accuracies (though it should still run).

Once I change the ImageNetApp to have the DataFrames store compressed images, training the full ImageNet dataset should work (right now it should work fine with 10% of the training data and all of the validation data).

**Comment by rahulbhalerao001** [comment] 2016-02-18 21:17
Hello Robert, 

Thank you for the update.
I have subscribed to all the updates of this Github project, and also want to ask some architectural/systems related questions about the proposed solution in #71.

Thanks,
Rahul

**Comment by robertnishihara** [comment] 2016-02-18 22:17
Great! Let's discuss that in #71.

**Comment by robertnishihara** [comment] 2016-03-23 22:00
Closing because the issues raised here are being discussed in separate issues. Feel free to reopen if something is unaddressed.

**Closed** 2016-03-23 21:59 UTC
